# Generated by Django 4.2.6 on 2023-10-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='nickname',
            field=models.CharField(default='', max_length=25),
        ),
    ]
