# Generated by Django 4.2.6 on 2023-10-21 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2023),
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('category', models.CharField(choices=[('G', 'Gasoline'), ('M', 'Maintenance'), ('I', 'Insurance'), ('T', 'Tolls'), ('P', 'Parking'), ('W', 'Car Wash'), ('R', 'Registration'), ('D', 'Depreciation'), ('O', 'Oil Changes'), ('E', 'Emissions Testing'), ('C', 'Car Loan Payments'), ('S', 'Tire Replacement'), ('A', 'Accessories'), ('V', 'Vehicle Inspection'), ('H', 'Highway Fees'), ('L', 'Lease Payments'), ('N', 'New Car Purchase'), ('F', 'Fines and Tickets'), ('X', 'Miscellaneous Expenses')], default='G', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=100)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.car')),
            ],
        ),
    ]
