# Generated by Django 4.2.6 on 2023-10-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_car_year_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='history',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='history',
            name='description',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
