# Generated by Django 4.2.6 on 2023-10-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_driver_alter_history_options_alter_history_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='drivers',
            field=models.ManyToManyField(to='main_app.driver'),
        ),
    ]
